# Generated by Django 5.0.1 on 2025-08-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='additional_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='analysis_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='full_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='investigation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='investigation_result',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='needs_investigation',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='scan_identifier',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_info',
            field=models.JSONField(default=dict),
        ),
    ]
