# Generated by Django 5.0.1 on 2026-01-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_phase2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='triage_confidence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='triage_interesting',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='triage_reason',
            field=models.TextField(null=True),
        ),
    ]
