# Generated by Django 5.0.1 on 2025-08-30 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveScanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('query', models.CharField(max_length=255)),
                ('status', models.CharField(default='stopped', max_length=20)),
            ],
            options={
                'verbose_name': 'Active Scanner',
                'verbose_name_plural': 'Active Scanners',
                'db_table': 'active_scanners',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('marketplace_url_slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='ScannerLocationMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.location')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.activescanner')),
            ],
            options={
                'verbose_name': 'Scanner Location Mapping',
                'verbose_name_plural': 'Scanner Location Mappings',
                'db_table': 'scanner_location_mappings',
                'unique_together': {('scanner', 'location')},
            },
        ),
        migrations.AddField(
            model_name='activescanner',
            name='locations',
            field=models.ManyToManyField(related_name='scanners', through='scanners.ScannerLocationMapping', to='scanners.location'),
        ),
    ]
