# Generated by Django 5.0.1 on 2025-08-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activescanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activescanner',
            name='updated_at',
        ),
    ]
