# Generated by Django 5.0.1 on 2025-08-30 02:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_remove_activescanner_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], max_length=10)),
                ('total_listings_found', models.IntegerField(default=0)),
                ('watchlist_items_added', models.IntegerField(default=0)),
                ('categories_scanned', models.JSONField(default=list, help_text='List of categories that were scanned')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scan_type', models.CharField(choices=[('continuous', 'Continuous'), ('single', 'Single')], default='single', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'get_latest_by': 'started_at',
            },
        ),
        migrations.AlterModelOptions(
            name='activescanner',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scannerlocationmapping',
            options={'ordering': ['location_name']},
        ),
        migrations.RemoveField(
            model_name='activescanner',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='scannerlocationmapping',
            name='is_active',
        ),
        migrations.AddField(
            model_name='activescanner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activescanner',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scannerlocationmapping',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scannerlocationmapping',
            name='location_name',
            field=models.CharField(default='Unknown', help_text='Cached location name for performance', max_length=255),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='marketplace_url_slug',
            field=models.CharField(help_text='URL slug for Facebook Marketplace', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Display name for the location', max_length=255),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_mappings', to='scanners.location'),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_mappings', to='scanners.activescanner'),
        ),
        migrations.AlterModelTable(
            name='activescanner',
            table=None,
        ),
        migrations.AlterModelTable(
            name='location',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scannerlocationmapping',
            table=None,
        ),
    ]
