# Generated by Django 5.0.1 on 2025-08-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0003_scanresult_alter_activescanner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='location_name',
            field=models.CharField(help_text='Cached location name for performance', max_length=255),
        ),
    ]
