# Generated by Django 5.0.1 on 2025-08-30 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0004_alter_activescanner_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScanResult',
        ),
        migrations.AlterModelOptions(
            name='activescanner',
            options={'verbose_name': 'Active Scanner', 'verbose_name_plural': 'Active Scanners'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='scannerlocationmapping',
            options={'verbose_name': 'Scanner Location Mapping', 'verbose_name_plural': 'Scanner Location Mappings'},
        ),
        migrations.RemoveField(
            model_name='activescanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activescanner',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scannerlocationmapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scannerlocationmapping',
            name='location_name',
        ),
        migrations.AddField(
            model_name='activescanner',
            name='locations',
            field=models.ManyToManyField(related_name='scanners', through='scanners.ScannerLocationMapping', to='scanners.location'),
        ),
        migrations.AddField(
            model_name='scannerlocationmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='status',
            field=models.CharField(default='stopped', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='marketplace_url_slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.location'),
        ),
        migrations.AlterField(
            model_name='scannerlocationmapping',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.activescanner'),
        ),
        migrations.AlterModelTable(
            name='activescanner',
            table='active_scanners',
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='scannerlocationmapping',
            table='scanner_location_mappings',
        ),
    ]
