# Generated by Django 5.0.1 on 2025-08-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0005_delete_scanresult_alter_activescanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('single', 'Single Scan'), ('continuous', 'Continuous Scan')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('scanners_processed', models.IntegerField(default=0)),
                ('total_listings_found', models.IntegerField(default=0)),
                ('new_listings_added', models.IntegerField(default=0)),
                ('watchlist_items_added', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('randomized', models.BooleanField(default=False)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan History',
                'db_table': 'scan_history',
                'ordering': ['-started_at'],
            },
        ),
    ]
