# Generated by Django 5.0.1 on 2025-08-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0006_add_scan_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('scan_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('scan_type', models.CharField(choices=[('single', 'Single'), ('continuous', 'Continuous')], default='single', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('total_listings_found', models.IntegerField(default=0)),
                ('new_listings_added', models.IntegerField(default=0)),
                ('investigation_marked', models.IntegerField(default=0)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_started_at', models.DateTimeField(null=True)),
                ('analysis_completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Scan Batch',
                'verbose_name_plural': 'Scan Batches',
                'db_table': 'scan_batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('current_item_title', models.CharField(max_length=200, null=True)),
                ('current_status', models.CharField(max_length=50, null=True)),
                ('estimated_completion', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scan_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='scanners.scanbatch')),
            ],
            options={
                'verbose_name': 'Analysis Progress',
                'verbose_name_plural': 'Analysis Progress',
                'db_table': 'analysis_progress',
            },
        ),
    ]
