# Generated by Django 5.0.1 on 2025-09-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0007_scanbatch_analysisprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='activescanner',
            name='max_mileage',
            field=models.IntegerField(blank=True, help_text='Maximum mileage filter for vehicles', null=True),
        ),
        migrations.AddField(
            model_name='activescanner',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price filter for good deals', max_digits=10, null=True),
        ),
    ]
