# Generated by Django 5.0.1 on 2025-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0008_activescanner_max_mileage_activescanner_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activescanner',
            name='max_distance',
            field=models.IntegerField(blank=True, help_text='Maximum distance from search location', null=True),
        ),
    ]
