# Generated by Django 5.0.1 on 2025-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0009_activescanner_max_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activescanner',
            name='category_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific filter criteria stored as JSON'),
        ),
        migrations.AddField(
            model_name='activescanner',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price filter', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activescanner',
            name='product_category',
            field=models.CharField(choices=[('vehicles', 'Vehicles'), ('skis', 'Skis & Snowboards'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('general', 'General')], default='general', help_text='Product category for category-specific filtering', max_length=50),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='category',
            field=models.CharField(help_text="User's custom category label", max_length=100),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='max_distance',
            field=models.IntegerField(blank=True, help_text='Maximum distance from search location in miles', null=True),
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='max_mileage',
            field=models.IntegerField(blank=True, help_text='DEPRECATED: Use category_filters.max_mileage instead', null=True),
        ),
    ]
