# Generated by Django 5.0.1 on 2026-01-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_phase2_fields'),
        ('scanners', '0010_add_multi_category_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescanner',
            name='product_category',
            field=models.CharField(choices=[('vehicles', 'Vehicles'), ('skis', 'Skis & Snowboards'), ('general', 'General'), ('ai_beta', 'AI Analysis (Beta)')], default='general', help_text='Product category for category-specific filtering', max_length=50),
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=50)),
                ('call_type', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('scan_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanners.scanbatch')),
            ],
            options={
                'verbose_name': 'LLM Usage',
                'verbose_name_plural': 'LLM Usage',
                'db_table': 'llm_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='llm_usage_created_c121ba_idx'), models.Index(fields=['agent_type'], name='llm_usage_agent_t_90efe9_idx'), models.Index(fields=['scan_batch'], name='llm_usage_scan_ba_fb21ab_idx')],
            },
        ),
    ]
