# Generated by Django 5.0.1 on 2026-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0011_alter_activescanner_product_category_llmusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activescanner',
            name='agent_type',
            field=models.CharField(choices=[('skis', 'Ski Equipment'), ('vehicles', 'Vehicles (Colorado 4x4)'), ('dj_equipment', 'DJ Equipment')], default='skis', help_text='Specialist agent type for AI-driven analysis', max_length=50),
        ),
    ]
