# Generated by Django 5.0.1 on 2026-01-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0012_activescanner_agent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=10)),
                ('auto_enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.IntegerField(default=30)),
                ('randomize_order', models.BooleanField(default=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('next_scan_at', models.DateTimeField(blank=True, null=True)),
                ('auto_process_pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scanner Settings',
                'verbose_name_plural': 'Scanner Settings',
                'db_table': 'scanner_settings',
            },
        ),
        migrations.CreateModel(
            name='SystemTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('scan', 'Marketplace Scan'), ('analysis', 'AI Analysis'), ('notification', 'Sending Notifications')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('current_step', models.CharField(choices=[('initializing', 'Initializing'), ('scraping', 'Scraping Listings'), ('saving', 'Saving to Database'), ('triaging', 'AI Triage (Pass 1)'), ('analyzing', 'Deep Analysis (Pass 2)'), ('notifying', 'Sending Notifications'), ('complete', 'Complete')], default='initializing', max_length=30)),
                ('progress_percent', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('scan_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanners.scanbatch')),
            ],
            options={
                'verbose_name': 'System Task',
                'verbose_name_plural': 'System Tasks',
                'db_table': 'system_tasks',
                'ordering': ['-started_at'],
            },
        ),
    ]
