# Generated by Django 5.0.1 on 2026-02-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0013_add_system_task_and_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activescanner',
            name='notification_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses to notify when this scanner finds deals'),
        ),
    ]
