# Generated by Django 5.0.1 on 2026-02-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0014_add_notification_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'Ski Equipment Specialist'", max_length=200)),
                ('slug', models.SlugField(help_text="Unique identifier, e.g. 'skis'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown in the UI agent card')),
                ('icon', models.CharField(default='🤖', help_text='Emoji icon for the agent', max_length=10)),
                ('triage_prompt', models.TextField(help_text='System prompt for Pass 1 (triage)')),
                ('analysis_prompt', models.TextField(help_text='System prompt for Pass 2 (deep analysis)')),
                ('triage_model', models.CharField(default='gemini-2.5-pro', max_length=100)),
                ('analysis_model', models.CharField(default='gemini-2.5-pro', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this agent is active')),
                ('is_system', models.BooleanField(default=False, help_text='True for built-in seeded agents (cannot be deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='agent_type',
            field=models.CharField(choices=[('skis', 'Ski Equipment'), ('vehicles', 'Vehicles (Colorado 4x4)'), ('dj_equipment', 'DJ Equipment')], default='skis', help_text='DEPRECATED: Use agent FK instead. Kept for backward compatibility.', max_length=50),
        ),
        migrations.AddField(
            model_name='activescanner',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Specialist agent for AI-driven analysis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanners', to='scanners.agent'),
        ),
    ]
