# Generated by Django 5.0.1 on 2026-02-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0016_seed_agents_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescanner',
            name='agent_type',
            field=models.CharField(blank=True, default='skis', help_text='Agent slug string. Synced with agent FK for backward compatibility.', max_length=100),
        ),
    ]
