# Generated by Django 5.0.1 on 2026-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0017_remove_agent_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Optional icon for the agent', max_length=10),
        ),
    ]
