# Generated by Django 5.0.1 on 2026-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0020_remove_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('current_task', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Worker Status',
                'verbose_name_plural': 'Worker Status',
                'db_table': 'worker_status',
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterField(
            model_name='activescanner',
            name='agent_type',
            field=models.CharField(blank=True, default='', help_text='Agent slug string. Synced with agent FK for backward compatibility.', max_length=100),
        ),
    ]
